# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Agencia', '0002_delete_avion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Agencia.Hotel')),
            ],
        ),
    ]
