# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyia', models.CharField(max_length=200)),
                ('origen', models.TextField()),
                ('destino', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('descripcion', models.TextField()),
                ('valor_Ciudad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField(default=0)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Agencia.Ciudad')),
            ],
        ),
    ]
