# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Agencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avion',
        ),
    ]
